version: '3.9'

services:
  db:
    image: postgres:14.4
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: cinema
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - postgres
    ports:
      - 5432:5432

networks:
  postgres:
    driver: bridge
