version: '3.9'

services:
  db:
    image: postgres:14.4
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 111
    volumes:
      - ./src/main/resources/sql/schema.sql:/docker-entrypoint-initdb.d/01_create_table.sql
      - ./src/main/resources/sql/data.sql:/docker-entrypoint-initdb.d/02_add_data_table.sql
    networks:
      - postgres
#    ports:
#      - "5432:5432"

  app:
    image: tomcat:9
    depends_on:
      - db
    container_name: app
    restart: always
    volumes:
      - ./target/cinema.war:/usr/local/tomcat/webapps/cinema.war
    networks:
      - postgres
    ports:
      - "8080:8080"

networks:
  postgres:
    driver: bridge
